# Detector
MAX_ANGLE = 0.8
MIN_EMBEDDING_NORM = 25
MIN_HEIGH_BOUDING_BOX_SIZE = 20
MIN_WIDTH_BOUDING_BOX_SIZE = 20
MIN_DIFF_HEIGH_WIDTH = 5
MIN_EYE_DISTANT = 12
DETECTOR_BATCH_SIZE = 20


# preprocessing
PYRAMID_IMAGE_THRESHOLD = [500,500]

IOU_THRESHOLD = 0.5
# Retinaface
RETINAFACE_THRESHOLD = 0.5
# SCALES_FIRST = [1024, 1980]
SCALES_FIRST = [512, 990]
RETINAFACE_NETWORK = "net3"
RETINAFACE_FLIP = False
MODEL_PATH = "/home/zdeploy/AILab/congvm/projects/RetinaFace/ckpt/retinaface/retinaface-R18/resnet18,0"